# Generated by Django 4.1.7 on 2023-06-07 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('access_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(default='anonymous', on_delete=models.SET('ANONYMOUS'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
